# Title     : www3.moneysmart.sg
# Objective : Data Team Coding Challenge
# Created by: parivallalr
# Created on: 02/11/18
# Load the libraries
library(arules)
library(dplyr)

#Load data set from csv file which is generated by Q2.scala
tdata <-read.transactions(file = '/tmp/Q2_itempair_tmp.csv', sep=",")
summary(tdata)

# creating rule on 'apriori' algorithm
rules <- apriori (tdata, parameter = list(supp = 0.001, conf = 0.5))
# apply rules
inspect(head(rules))



# Sample Output as below,

# lhs                                                               rhs                          support     confidence lift     count
# [1] {}                                                             => {1}                          0.943396226 0.9433962  1.000000 450
# [2] {Wilson Jones Hanging View Binder, White, 1",1}                => {Staple envelope}            0.002096436 1.0000000  5.611765   1
# [3] {Office Impressions End Table, 20-1/2H x 24W x 20D,1}          => {KI Adjustable-Height Table} 0.002096436 1.0000000  9.937500   1
# [4] {ACCOHIDE 3-Ring Binder, Blue, 1",1}                           => {Staple envelope}            0.002096436 1.0000000  5.611765   1
# [5] {Seth Thomas 13 1/2 Wall Clock,1}                              => {Staples}                    0.002096436 1.0000000  4.917526   1
# [6] {Avery Framed View Binder, EZD Ring (Locking), Navy, 1 1/2",1} => {Staples}                    0.002096436 1.0000000  4.917526   1








